version: '3'

services:
  nginx:
    restart: always
    build: ./docker-files/nginx
    volumes: 
      - ./docker-files/nginx/:/etc/nginx/conf.d
      - static:/code/static_cdn
      - media:/code/media_cdn
    ports: 
      - "80:80"
    networks:
      - inside

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - inside
    env_file:
      - docker-files/db/.env

  web:
    build: 
      context: stageit/.

    volumes:
      - static:/code/static_cdn
      - media:/code/media_cdn
    depends_on:
      - db
    command: bash -c "/usr/src/app/entrypoint.sh && python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 wsgi -k gevent -b 0.0.0.0:8000"
    networks:
      - inside
    env_file:
      - stageit/.env.dev

  celery:
    build: stageit/.
    command: celery -A stageit worker -l info
    depends_on:
      - db
      - rabbit
      - web
    networks:
      - inside

  rabbit:
    image: rabbitmq:3
    networks:
      - inside

volumes:
  postgres-data:
  media:
  static:

networks:
  inside: