# Generated by Django 3.0.3 on 2020-03-02 22:06

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapConfig',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('bootstraptemplate', models.TextField()),
                ('values', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('md5', models.TextField()),
                ('sha256', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateend', models.DateTimeField(null=True)),
                ('datestart', models.DateTimeField(null=True)),
                ('description', models.TextField(max_length=50)),
                ('installmode', models.TextField(max_length=20)),
                ('model', models.TextField(max_length=50)),
                ('os_version', models.TextField(max_length=300)),
                ('rundata', models.BinaryField(editable=True, max_length=1024000, null=True)),
                ('serial', models.TextField(max_length=20)),
                ('template', models.TextField(max_length=20000)),
                ('templatevalues', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('vendor', models.TextField(max_length=30)),
                ('status', models.TextField(null=True)),
                ('workerid', models.TextField(null=True)),
                ('fktask', models.TextField()),
                ('fkserialport', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='RemoteWorker',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fkuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TerminalServer',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('model', models.TextField()),
                ('hostname', models.TextField(unique=True)),
                ('transport', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('fkremoteworker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_interface.RemoteWorker')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('filepath', models.TextField(max_length=256, null=True)),
                ('installmode', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=50, unique=True)),
                ('platform', models.TextField(max_length=30, null=True)),
                ('poststaging', models.TextField(max_length=1000)),
                ('template', models.TextField(max_length=500000)),
                ('templatevalues', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('fkbootstrapconfig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web_interface.BootstrapConfig')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('taskvalues', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('fktemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('log', models.TextField(null=True)),
                ('logdate', models.DateTimeField(auto_now_add=True)),
                ('fkhistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.History')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='fkremoteworker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_interface.RemoteWorker'),
        ),
        migrations.CreateModel(
            name='SerialPort',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport', models.TextField()),
                ('port', models.IntegerField()),
                ('line', models.IntegerField()),
                ('fkterminalserver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_interface.TerminalServer')),
            ],
            options={
                'unique_together': {('fkterminalserver', 'port')},
            },
        ),
    ]
