# Generated by Django 3.0.2 on 2020-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteworker',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
