# Generated by Django 3.0.2 on 2020-02-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_auto_20200220_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='fkremoteworker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_interface.RemoteWorker'),
            preserve_default=False,
        ),
    ]
