serials:
  - hostname: "10.82.135.2"
    port: 2033
    transport: telnet
    line: 33
    model: cisco
  - hostname: "10.82.135.2"
    port: 2034
    transport: telnet
    line: 34
    model: cisco

console_server:
  "10.82.135.2":
    model: cisco
    transport: telnet
    username: cisco
    password: cisco