# Generated by Django 2.2.4 on 2019-08-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('pkid', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('installmode', models.TextField(max_length=20)),
                ('model', models.TextField(max_length=50)),
                ('os_version', models.TextField(max_length=300)),
                ('rundata', models.BinaryField(editable=True, max_length=1024000)),
                ('serial', models.TextField(max_length=20)),
                ('serial_number', models.TextField(max_length=50)),
                ('template', models.TextField(max_length=20000)),
                ('templatevalues', models.BinaryField(editable=True)),
                ('vendor', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('pkid', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('filepath', models.TextField(max_length=256)),
                ('installmode', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=50, unique=True)),
                ('platform', models.TextField(max_length=30)),
                ('poststaging', models.TextField(max_length=1000)),
                ('template', models.TextField(max_length=500000)),
                ('templatevalues', models.BinaryField(editable=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('pkid', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('taskvalues', models.BinaryField(editable=True)),
                ('fktemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stageit.Templates')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('log', models.TextField()),
                ('logdate', models.DateTimeField(auto_now_add=True)),
                ('fkhistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stageit.History')),
            ],
        ),
    ]
