# Generated by Django 2.2.4 on 2019-08-13 18:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stageit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='templatevalues',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskvalues',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='templates',
            name='templatevalues',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
